# Generated by Django 3.2.19 on 2023-05-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='no',
        ),
    ]
